[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]

[bans]
wildcards = "deny"
external-default-features = "deny"

[bans.build]
allow-build-scripts = [
    # https://docs.rs/crate/libc/0.2.104/source/build.rs
    { name = "libc" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
