name: setup-libmagic
description: Setup some version of `libmagic` for `magic-sys`

runs:
  using: 'composite'
  steps:
    # setup cache
    - name: setup cache
      if: ${{ runner.os == 'Windows' }}
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');


    # update packages

    - name: update packages
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get update
      shell: bash

    - name: update packages
      if: ${{ runner.os == 'Windows' }}
      run: vcpkg update
      shell: bash

    - name: update packages
      if: ${{ runner.os == 'macOS' }}
      run: brew update
      shell: bash


    # install packages

    - name: install packages
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install libmagic1 libmagic-dev pkg-config
      shell: bash

    - name: install packages
      if: ${{ runner.os == 'Windows' }}
      run: |
        vcpkg install libmagic:x64-windows-static-md
        echo "VCPKG_ROOT=${VCPKG_INSTALLATION_ROOT}" >> "${GITHUB_ENV}"
      shell: bash

    - name: install packages
      if: ${{ runner.os == 'macOS' }}
      run: brew install libmagic pkg-config
      shell: bash


    # setup environment

    - name: setup environment
      if: ${{ runner.os == 'Linux' }}
      run: echo "VCPKGRS_NO_LIBMAGIC=1" >> "${GITHUB_ENV}"
      shell: bash

    - name: setup environment
      if: ${{ runner.os == 'Windows' }}
      run: echo "LIBMAGIC_NO_PKG_CONFIG=1" >> "${GITHUB_ENV}"
      shell: bash

    - name: setup environment
      if: ${{ runner.os == 'macOS' }}
      run: echo "VCPKGRS_NO_LIBMAGIC=1" >> "${GITHUB_ENV}"
      shell: bash

    # setup static build

    - name: setup static build
      if: ${{ runner.os == 'Linux' }}
      run: echo "LIBMAGIC_STATIC=1" >> "${GITHUB_ENV}"
      shell: bash

    - name: setup static build
      if: ${{ runner.os == 'Windows' }}
      run: echo "Static builds are the default for vcpkg-rs"
      shell: bash

    - name: setup static build
      if: ${{ runner.os == 'macOS' }}
      run: echo "LIBMAGIC_STATIC=1" >> "${GITHUB_ENV}"
      shell: bash
