name: "build-extra"

permissions: {}

on:
  # run on default branch to store caches
  push:
    branches: [ main ]
  pull_request:

jobs:
  cargo-vcpkg-extra:
    name: "cargo vcpkg && cargo test"
    permissions:
      contents: read
    runs-on: windows-latest
    steps:
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - id: toolchain
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # doesn't have usual versioned releases/tags
        with:
          toolchain: "1.88.0" # current pinned stable
          # minimal profile includes rustc component which includes cargo and rustdoc

      - uses: rui314/setup-mold@702b1908b5edf30d71a8d1666b724e0f0c6fa035 # does not have recent tags

      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

      - uses: taiki-e/install-action@8520ed0913d842fe1061358cb4d010ef346b0ea9 # v2.56.16
        with:
          # renovate: taiki-e/install-action
          tool: cargo-vcpkg@0.1.7

      - run: cargo +${{ steps.toolchain.outputs.name }} vcpkg --verbose build

      - run: cargo +${{ steps.toolchain.outputs.name }} test --all-targets --all-features --verbose
