name: "conventional commits"

permissions: {}

on:
  pull_request:

jobs:
    cog-check:
        name: "cog check"
        permissions:
          contents: read
        runs-on: ubuntu-24.04
        steps:
            - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
              with:
                egress-policy: audit

            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                persist-credentials: false
                fetch-depth: 0
                # pick the pr HEAD instead of the merge commit
                ref: ${{ github.event.pull_request.head.sha }}

            - uses: taiki-e/install-action@cbbd2313f89ec137914d3e35d4669f76aca5c947 # v2.58.26
              with:
                # renovate: taiki-e/install-action
                tool: cocogitto@6.0.0

            - run: cog check ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
