name: "MSRV"

permissions: {}

on:
  pull_request:

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_INCREMENTAL: "false"
  CARGO_PROFILE_TEST_DEBUG: "false"
  CARGO_TERM_VERBOSE: "true"
  CARGO_TERM_COLOR: "always"

jobs:
  cargo-msrv:
    name: "cargo msrv"
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      # install toolchain/rustup for running `cargo msrv` itself
      # https://github.com/foresterre/cargo-msrv/blob/main/README.md#prerequisites
      - id: toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # doesn't have usual versioned releases/tags
        with:
          toolchain: "1.88.0" # current pinned stable

      - run: echo "RUSTUP_TOOLCHAIN=${RUSTUP_TOOLCHAIN}" >> "${GITHUB_ENV}"
        env:
          RUSTUP_TOOLCHAIN: ${{ steps.toolchain.outputs.name }}

      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0 

      - uses: ./.github/actions/setup-libmagic

      - uses: taiki-e/install-action@f63c33fd96cc1e69a29bafd06541cf28588b43a4 # v2.58.21
        with:
          # renovate: taiki-e/install-action
          tool: cargo-msrv@0.18.4

      - run: cargo msrv --version
      - run: cargo msrv verify --output-format json -- cargo test --locked --all-targets --all-features
      - if: ${{ failure() }}
        run: cargo msrv find --output-format json -- cargo test --locked --all-targets --all-features
