name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-libmagic
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
