name: zizmor GHA SAST

permissions: {}

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  zizmor:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: zizmorcore/zizmor-action@f52a838cfabf134edcbaa7c8b3677dde20045018 # v0.1.1
        with:
          version: latest
